services:
  server:
    image: ghcr.io/matsubara0507/jobworker:latest
    deploy:
      replicas: 1
    command: [--verbose, --port, "8080", "/var/jobs.yaml"]
    volumes:
      - ./jobs.yaml:/var/jobs.yaml
    ports:
      - 8080:8080

  runner:
    image: ghcr.io/matsubara0507/jobworker-runner:latest
    deploy:
      replicas: 3
    depends_on:
      - server
    command: [--verbose, server:8080/runner]
