name:                jobworker
version:             0.1.0
github:              "matsubara0507/jobworker.hs"
license:             BSD3
author:              "MATSUBARA Nobutada"
maintainer:          "nobutada0507@gmail.com"
copyright:           "2022 MATSUBARA Nobutada"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/matsubara0507/jobworker.hs#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path

default-extensions:
- GHC2021
- DataKinds
- NoFieldSelectors
- OverloadedRecordDot
- OverloadedStrings

dependencies:
- aeson
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- http-api-data
- random
- servant-server
- servant-websockets
- stm
- text
- websockets
- yaml

library:
  source-dirs: src

executables:
  jobworker:
    main:                Main.hs
    source-dirs:         app/server
    dependencies:
    - jobworker
    - warp
  jobworker-runner:
    main:                Main.hs
    source-dirs:         app/runner
    dependencies:
    - jobworker

tests:
  jobworker-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - jobworker
